rm -r minified_building_footprints
mkdir minified_building_footprints

python reduce_coordinate_precision.py MB.geojson 7
python remove_fields_from_geojson.py MB_reduce_coord_precision.geojson "Longitude,Latitude,Build_ID,Shape_Leng,Shape_Area"
python remove_duplicate_geometries.py MB_reduce_coord_precision_removed_fields.geojson

mv unique_MB_reduce_coord_precision_removed_fields.geojson ./minified_building_footprints/MB.geojson
rm MB_reduce_coord_precision_removed_fields.geojson
rm MB_reduce_coord_precision.geojson

python reduce_coordinate_precision.py SK.geojson 7
python remove_fields_from_geojson.py SK_reduce_coord_precision.geojson "Longitude,Latitude,Build_ID,Shape_Leng,Shape_Area"
python remove_duplicate_geometries.py SK_reduce_coord_precision_removed_fields.geojson

mv unique_SK_reduce_coord_precision_removed_fields.geojson ./minified_building_footprints/SK.geojson
rm SK_reduce_coord_precision_removed_fields.geojson
rm SK_reduce_coord_precision.geojson
